### PR TITLE
mark recent moves in player area and research board

### LINKED ISSUE #12: show more recent actions
# player board

research area:

image

buildings

image
image

# board actions

only the recent ones - you already know if they're taken in the current round

image

or 

image

image

https://user-images.githubusercontent.com/2832627/108954291-e4141900-766c-11eb-89c1-03ed77b79c7a.mp4

### PR DESCRIPTION
**Pull request by zeitlinger**
Fixes #12

### CODE REVIEW

**Comment by coyotte508** [comment]
This looks good!

The failing test is unfortunate, now that `BoardAction` uses getters. I don't really know how to fix it, maybe removing the store's namespacing (would change all the `store.state.gaiaViewer` to `store.state`) would do it.

Or maybe you can overwrite the getters manually:

```
(store as any).getters = { "gaiaViewer/recentCommands": () => [] };
```

instead of

```
delete (store as any).getters;
```

**Comment by zeitlinger** [comment]
> This looks good!
> 
> The failing test is unfortunate, now that `BoardAction` uses getters. I don't really know how to fix it, maybe removing the store's namespacing (would change all the `store.state.gaiaViewer` to `store.state`) would do it.
> 
> Or maybe you can overwrite the getters manually:
> 
> ```
> (store as any).getters = { "gaiaViewer/recentCommands": () => [] };
> ```
> 
> instead of
> 
> ```
> delete (store as any).getters;
> ```

that was a good idea.

I changed the animations again - now rotating around the Y axis, which makes it clearer.

However, the animations are not synchronized - we might want to add https://github.com/bealearts/css-animation-sync - but I'm not sure.

**Comment by coyotte508** [comment]
https://github.com/bealearts/css-animation-sync looks like a lightweight dependency. But I'm not sure if it works to sync different animations that have the same duratoin (and do we need that?). 

Anyway for now the player can probably disable/enable recent moves to reset the animations so that they run at the same time. Don't hesitate to make a PR with sync though - but it would *maybe* need altering the code of the library so that we can sync different animations.

**Comment by zeitlinger** [comment]
> https://github.com/bealearts/css-animation-sync looks like a lightweight dependency. But I'm not sure if it works to sync different animations that have the same duratoin (and do we need that?).
> 
> Anyway for now the player can probably disable/enable recent moves to reset the animations so that they run at the same time. Don't hesitate to make a PR with sync though - but it would _maybe_ need altering the code of the library so that we can sync different animations.

na - let's see how it works out in practice first

**Pull request merged**
