### PR TITLE
make replay more permissive

### LINKED ISSUE #158: Replay is bugged in certain games
https://www.boardgamers.space/game/Pink-redundancy-941

I tried viewing this game's replay and it stopped after 52/432 in the replay bar. Nothing happened after that, it went to 53,54,55... but there was no movement on the map or in the log. This has happened previously in some games, one such game is https://www.boardgamers.space/game/Telling-secretary-320 

In the second link, it stops in the 90's (94/190 or something if I remember right).

### PR DESCRIPTION
**Pull request by zeitlinger**
Maybe fixes #158

### CODE REVIEW

**Comment by coyotte508** [comment]
Nice!

I feel a bit bad about carring the "replay" parameter in a lot of places in the engine code - I feel like maybe it could be an global context variable (since no engine calls are async) - that would be returned by a `isReplay()` function.

But it can be refacto later if needed :)

**Review by coyotte508 — APPROVED** [review]

**Comment by zeitlinger** [comment]
> Nice!
> 
> I feel a bit bad about carrying the "replay" parameter in a lot of places in the engine code - I feel like maybe it could be an global context variable (since no engine calls are async) - that would be returned by a `isReplay()` function.
> 
> But it can be refacto later if needed :)

such global state makes tests harder to get right...

**Comment by Zevenberge** [comment]
> Nice!
> 
> I feel a bit bad about carrying the "replay" parameter in a lot of places in the engine code - I feel like maybe it could be an global context variable (since no engine calls are async) - that would be returned by a `isReplay()` function.
> 
> But it can be refacto later if needed :)

Is this because we don't want the replay to brick if the rules change slightly? Can't we centralize all checks in the engine and do something like

```Typescript
build(move) {
    const moves = availableBuildings();
    enforceAllowed(move, moves);
    execute(move);
}

enforceAllowed(move, moves) {
    if(this.isReplay) return;
    assert(moves.some(m => m == move));
}
```

**Comment by coyotte508** [comment]
For sure, splitting the checking part from the action would help, maybe even replacing `assert` by `this.assert` in the engine (and it would only trigger when not in a replay)

**Comment by zeitlinger** [comment]
> For sure, splitting the checking part from the action would help, maybe even replacing `assert` by `this.assert` in the engine (and it would only trigger when not in a replay)

thought about that as well - some checks are done in player, available-commands instead of engine.

Maybe it should be all moved to available-commands.

I wouldn't blindly ignore all asserts - that is easy to forget, but if we call it something like "softAssert" it should be fine.

**Comment by zeitlinger** [comment]
> Is this because we don't want the replay to brick if the rules change slightly?

Yes, from all the 20k games there are still 173 games which could not be replayed - but I haven't figured out why.

**Pull request merged**
